name: PHP Syntax Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    name: PHP Syntax Validation

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: dom, curl, libxml, mbstring, zip
        coverage: none

    - name: PHP Syntax Check
      run: |
        find . -name "*.php" -exec php -l {} \;

    - name: Check plugin file exists
      run: |
        if [ ! -f "woocommerce-fraud-shield.php" ]; then
          echo "Main plugin file not found"
          exit 1
        fi
        echo "Plugin structure validation passed"